apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Infra Tasks
  - infra/image-builder.yaml
# Golang
  - be-golang/build-config.yaml
# Python
  - be-python/build-config.yaml
# Rust
  - be-rust/build-config.yaml
# Frontend
  - fe-node/build-config.yaml
# Infra Tasks
  - infra/route-fe.yaml
  - infra/service.yaml

# namespace: ocp-demo
